### ISSUE TITLE
Add local image support for authors, currently we are fetching author image from github

### ISSUE THREAD

**Issue by puneetsingh24** [LoginRadius/engineering-portal#228]
Create a folder in content/assets folder for author images, then need to mention the image name for the respective author in content/author.yaml

And that author image will be displayed at the blog listing/blog detail and author page.

**Comment by Ruchika30** [comment]
Hello @puneetsingh24 . I would like to take this up

**Comment by vyasriday** [comment]
Assigned you @Ruchika30. Thanks for contributing!

LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.
https://www.loginradius.com/engineering/page/hacktoberfest2020

**Comment by Ruchika30** [comment]
@puneetsingh24  How do I run those graphql queries

**Comment by mohammed786** [comment]
Hey @Ruchika30 ,

Once you setup the project in the local you can try the graphql queries in the [localhost:8000/__graphql](http://localhost:8000/__graphql) playground provided by gatsby.

Also, gatsby provides a playground where you can try those queries without setting up the project. Checkout [here](https://graphql-reference-1124782374.gtsb.io/___graphql).

I hope it's clear now, feel free to ask any more questions if you have.

**Comment by Ruchika30** [comment]
@mohammed786 When I try to raise PR of my branch(addImageFolder) against dev, it says there is nothing to compare. And hence I am unable to do raise the Pr. Kindly help

**Comment by Ruchika30** [comment]
Hello @mohammed786 . Required changes done ..Kindly review 
8c766cc4761914c05fdc8b419ab4ca464d861d5d

**Comment by Ruchika30** [comment]
Hello @mohammed786 . Though I raised the PR I cannot see any update regarding it in my hacktoberfest profile. Is there something thats needs to be done from your side. Like **adding** **hacktoberfest-accepted**  label or something llike that.
Would u pls help
