### ISSUE TITLE
Add support for GIF Images in blog

### ISSUE THREAD

**Issue by pareek-narendra** [LoginRadius/engineering-portal#229]
Right now GIF Images are not supported with our blog content, Add support for GIF images along with other formats.

**Comment by pranavp10** [comment]
I would like to work on this

**Comment by pareek-narendra** [comment]
Assigned you @pranavp10 . Thanks for contributing!

LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.
https://www.loginradius.com/engineering/page/hacktoberfest2020

**Comment by pranavp10** [comment]
@pareek-narendra  working on it

**Comment by pranavp10** [comment]
@pareek-narendra @puneetsingh24  do take a look at the pull request I have added support for the GIF Images in the blog  [reference](https://github.com/gatsbyjs/gatsby/issues/7317#issuecomment-412984851)

**Comment by pranavp10** [comment]
> Assigned you @pranavp10 . Thanks for contributing!
> 
> LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.
> https://www.loginradius.com/engineering/page/hacktoberfest2020

i did not recive any free goodies that you had quoted in the comment that i had registered for :( sad to say this

**Comment by puneetsingh24** [comment]
@pranavp10 Pranav there was a google form on the above-mentioned link, you needed to submit your info(as mentioned in above message), we didn't get any entry from your id, maybe that's the reason you didn't receive any communication from our side.

**Comment by pranavp10** [comment]
I got the mail form hridayesh.sharma@loginradius.com i did submit the the shipping details but still no reply !!!
