### ISSUE TITLE
Need to show the reading minutes on the blog detail page

### ISSUE THREAD

**Issue by puneetsingh24** [LoginRadius/engineering-portal#230]
Need to show how much minutes approximately it will take to read the blog post, Need to put "x min read" just after where the date is showing in a blog post.

**Comment by Kalovelo** [comment]
hello  :wave: @puneetsingh24 , could I work on this issue for hacktoberfest2020 :tada: ?

**Comment by puneetsingh24** [comment]
@Kalovelo Assigned issue to you for hacktoberfest2020 

And LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

**Comment by abhaybhatt** [comment]
@puneetsingh24  can i contribute to this issue?

**Comment by Kalovelo** [comment]
Hello, sorry for the inconvinience I will fulfill the extra requirements and update the PR within the day!
