### ISSUE TITLE
Need to update the dimension of the cover image

### ISSUE THREAD

**Issue by puneetsingh24** [LoginRadius/engineering-portal#231]
https://www.loginradius.com/engineering/blog/getting-started-with-grpc-part-1-concepts/

The cover image for the above blog is blurred and of not recommended size, You can upload a new image or update the cover image of above mention blog to 3:2 ratio and minimum size to 1200px:800px

**Comment by Ashumaurya** [comment]
I would like to work on this issue.

**Comment by puneetsingh24** [comment]
@Ashumaurya assigned the issue to you for hacktoberfest2020

And LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

**Comment by Ashumaurya** [comment]
@puneetsingh24  Thankyou for assigning this issue to me and also letting me know about the free goodies from your side.

**Comment by abhaybhatt** [comment]
@puneetsingh24  can i be assigned for this issue?

**Comment by puneetsingh24** [comment]
Issue has done
