### ISSUE TITLE
Code Duplication - GraphQL queries are duplicated at many places in the templates, Removing those duplicate queries will increase code quality

### ISSUE THREAD

**Issue by aman-agrwl-zz** [LoginRadius/engineering-portal#232]
Code Duplication - GraphQL queries are duplicated at many places in the templates. 

Remove those duplicate quires will increase code quality,

**Comment by sjha2048** [comment]
Hi @aman-agrwl , I would like to take up this issue, can you please assign it to me?

**Comment by aman-agrwl** [comment]
@sjha2048  Assigned issue to you for hacktoberfest2020

And LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

**Comment by gagandeepp** [comment]
@aman-agrwl-zz  is this still open I am interested in working on this
