### ISSUE TITLE
Write a technical blog on any technology of your choice and get swags. 

### ISSUE THREAD

**Issue by pareek-narendra** [LoginRadius/engineering-portal#233]
LoginRadius is accepting guest blogs on its Engineering Blog. Feel free to write a blog on any technology of your choice and comment on the issue. 
### You don't need to be an assignee on the issue to write blog. Plese raise a PR once done and comment here. 

Check out our Hacktoberfest Page before https://www.loginradius.com/engineering/page/hacktoberfest2020.

Engineering Blog
https://www.loginradius.com/engineering/blog/

Our Contribution Guideline
https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md

Happy Blogging! 

**Note: As part of our code of conduct we encourage you to create your own content in your own language. We are strongly against plagiarism and hence do not accept blogs that do not follow our contribution guidelines.**

**If you need any help from us with respect to writing your blog, we will happy to help. But please make sure your content is not copy-pasted from the internet. If found so, we will close your pull request with prior notice.**

**Comment by arshita129** [comment]
Hey! I would like to contribute by writing a blog under Hacktoberfest 2020.

**Comment by pareek-narendra** [comment]
@arshita129 assigned the issue to you for hacktoberfest2020

And LoginRadius is also giving swags to people who are contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

**Comment by Ninjavin** [comment]
Hey @pareek-narendra I would like to write a blog. Can you please assign this to me?

**Comment by vyasriday** [comment]
@Ninjavin Please feel free to write one and let us know here once you raise a PR. Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well. Happy Writing :)

**Comment by heytulsiprasad** [comment]
Hey @pareek-narendra, thanks for this opportunity. I would love to write for your blog and be a part of this community. :heart:

You can check my written blogs on, [Wirescript](https://wirescript.now.sh) (my small home on internet). I have read your contribution guidelines, its great by me. 👍

**Comment by kichloo** [comment]
@vyasriday @pareek-narendra Can this issue have multiple assignes, because I too want to submit a technical blog.

**Comment by vyasriday** [comment]
@kichloo @heytulsiprasad Yeah you can also write your blog with us. Just Raise a PR and let us know here. 
Happy Blogging!

**Comment by kichloo** [comment]
@vyasriday Thanks! But, I had a question, how to write a blog, i.e. we have to write and submit the blog on the website or prepare it on MS Word and other mediums and then submit?

**Comment by vyasriday** [comment]
@kichloo We accept in the MD format.  You can know more about it [here](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md). Let me know if you need further help.

**Comment by khushijindal** [comment]
Hey @pareek-narendra! I would like to contribute a blog here for hacktoberfest 2020. This would be my first contribution to a public repo XD.

**Comment by imrishabh18** [comment]
I am starting to write a blog as well 😄

**Comment by pareek-narendra** [comment]
@khushijindal @imrishabh18 Please feel free to write one and let us know here once you raise a PR. Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well. Happy Writing :)

**Comment by eaglewarrior** [comment]
I want to write a ML blog please assign me issue

**Comment by vyasriday** [comment]
@eaglewarrior Assigned you as well. Thanks for contributing. Please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to learn more about getting swags from LoginRadius

**Comment by aknrg77** [comment]
Hi @vyasriday I would like to write a blog, please assign me this issue.

**Comment by KarenEfereyan** [comment]
@vyasriday the article can be on any kind of technology, right?

**Comment by vyasriday** [comment]
@aknrg77 Sure, I will add you as assginee too. LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.
https://www.loginradius.com/engineering/page/hacktoberfest2020

**Comment by Hard-Coder05** [comment]
@vyasriday I am interested to write a blog on Flutter! Could you please assign me this issue?

**Comment by pareek-narendra** [comment]
@Hard-Coder05 Great, I will add you as assignee too. LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

Happy Writing :)

**Comment by anup-a** [comment]
@pareek-narendra  Can I write a blog on **GraphQL** ? Did quite a research a while back

**Comment by ashish8947** [comment]
Yeah sure @anup-a, I will add you as assignee too. LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

Happy Writing :)

**Comment by Hard-Coder05** [comment]
@ashish8947 @vyasriday @pareek-narendra I have raised a PR #254  for this issue. I have completed my blog!

**Comment by iamshubhankarkhare** [comment]
@ashish8947  @pareek-narendra I would love to write a blog on **VIM** .Can you please assign this to me as well ?? TIA

**Comment by ashish8947** [comment]
Yeah sure @iamshubhankarkhare, I will add you as assignee too. LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

Happy Writing :)

**Comment by vyasriday** [comment]
@Hard-Coder05 Thanks for contributing. I will put your PR under Review. :)

**Comment by agarwalBinay18** [comment]
I want to work on this issue.please assign me

**Comment by Dabjazz** [comment]
Sir, I would like to work on this issue. I would like to share my knowledge of getting started with Game Development.

**Comment by ramesht007** [comment]
hello @pareek-narendra , I want to work on this PR.

**Comment by KarenEfereyan** [comment]
@pareek, I don't have to be assigned to work on this right?

**Comment by dhritippaul** [comment]
Hello @pareek-narendra , I will like to contribute to your blog . I would be following the contributing guide as mentioned. Kindly assign me the blog writing part so that I can continue with writing blog .

**Comment by subhadeeppaul** [comment]
Hello @pareek-narendra , I would love to write for your blog for hactoberfest 2020 and be a part of this community. Can you please assign me?

**Comment by HunainHumail** [comment]
Hello @pareek-narendra  I would love to write a blog on technology and development for hacktoberfest 2020. Please assign me so that I can also contribute

**Comment by elfreki** [comment]
#268 Creted a post request for a blog

**Comment by iamshubhankarkhare** [comment]
@pareek-narendra @ashish8947  I just finished writing the blog on **VIM: Getting started** . Its PR #279 .
Please have a look.

**Comment by Harshsngh07** [comment]
Hi, @pareek-narendra would like to write a blog on competitive programming for hacktoberfest 2020. Please assign me so that I can also contribute

**Comment by pareek-narendra** [comment]
Yeah sure @Harshsngh07 , I will add you as assignee too. LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

Happy Writing :)

**Comment by KarenEfereyan** [comment]
@pareek-narendra assign me also

**Comment by pareek-narendra** [comment]
Sure @KarenEfereyan 
LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

Happy Writing :)

**Comment by agarwalBinay18** [comment]
@pareek-narendra Please review my PR :)

**Comment by dhritippaul** [comment]
> Hello @pareek-narendra , I woudl like to contribute to your blog . I would be following the contributing guide as mentioned. Kindly assign me the blog writing part so that I can continue with writing blog .

@pareek-narendra kindly assign me the same sir

**Comment by ashish8947** [comment]
Sure @dhritippaul assigning to you
LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

Happy Writing :)

**Comment by arshita129** [comment]
Hey! Please review my PR

**Comment by alok182011** [comment]
Hey! Can you assign me this? I'll like to contribute a blog on react events.

**Comment by puneetsingh24** [comment]
Sure @alok182011 assigning to you
LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

Happy Writing :)

**Comment by Garvit-32** [comment]
Hi @puneetsingh24 I would love to contribute, Can you assign me on this.

**Comment by akshay11298** [comment]
Hi @puneetsingh24 I have written a blog and created pr #298 for it. Could you please assign this to me as well

**Comment by SamriddhiMishra** [comment]
Hi, @puneetsingh24 I have created the pr #299. Please review it. Thanks!

**Comment by puneetsingh24** [comment]
Yeah sure @Garvit-32, Added you as assignee too. LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

Happy Writing :)

**Comment by eaglewarrior** [comment]
Hi @puneetsingh24 @vyasriday @pareek-narendra  I have raised a PR #303 please review and let me know the changes

**Comment by puneetsingh24** [comment]
Hello, @Dabjazz @ramesht007 @subhadeeppaul @HunainHumail Thanks for your interest in writing the blog. Please feel free to write one and let us know here once you raise a PR. 

Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well. Happy Writing :)

**Comment by agarwalBinay18** [comment]
@puneetsingh24  please check my PR :)

**Comment by shraddhavp** [comment]
would like to write a technical blog can you please assign @puneetsingh24

**Comment by puneetsingh24** [comment]
Hello, @shraddhavp  Thanks for your interest in writing the blog. Please feel free to write one and let us know here once you raise a PR.

Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well. Happy Writing :)

**Comment by shaswatsingh19** [comment]
Hey! @pareek-narendra  I would like to contribute by writing a blog can you please assign it to me

**Comment by puneetsingh24** [comment]
Hello, @shaswatsingh19  Thanks for your interest in writing the blog. Please feel free to write one and let us know here once you raise a PR.

Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well. Happy Writing :)

**Comment by rjn01** [comment]
@pareek-narendra @puneetsingh24  I would like to write a blog can you please assign it to me.

**Comment by subhadeeppaul** [comment]
> Hello @pareek-narendra , I would love to write for your blog for hacktoberfest 2020 and be a part of this community. Please assign me so that I can continue with writing blog.

@pareek-narendra kindly assign me the same sir

**Comment by GunjanMA** [comment]
Hello @pareek-narendra !!! I would like to contribute by writing a blog... please assign me the issue

**Comment by eaglewarrior** [comment]
Hi @puneetsingh24 @vyasriday @pareek-narendra I have raised a PR #326  please review and let me know the changes, I have raised this issue again as I have wrongly raised or from my master to login dev, now corrected to my dev to login radius dev.

**Comment by markandevansh99** [comment]
Hey! @pareek-narendra @puneetsingh24 ..I have raised a PR #344 by contributing a Blog..Please review it.

**Comment by Sheetal777** [comment]
Hello Maintainers. Would like to write a blog and raise the PR soon. 
Thank you!

**Comment by Malvika18** [comment]
hey i would also like to write one blog

**Comment by hacky1997** [comment]
@pareek-narendra @puneetsingh24 @vyasriday Hello everyone, I also want to contribute by writing some on the latest techs. Could you guys assign me too?

**Comment by king-11** [comment]
@pareek-narendra I was thinking I can write a blog about query optimizations in Django or maybe cryptographically hashing API key files in nodejs can I go ahead with one of them ?

**Comment by parasgoyal12** [comment]
@puneetsingh24 @vyasriday @pareek-narendra I want to Write a Blog on Competitive Programming. Please assign to me.

**Comment by rjn01** [comment]
@puneetsingh24 @pareek-narendra I have written a blog. Please review my PR #346

**Comment by jnvee** [comment]
@puneetsingh24 @vyasriday @pareek-narendra Hello i would like to write a blog and this is my first time contributing to open source as a part of HacktoberFest! Would you please assign it to me?

**Comment by vyasriday** [comment]
@jnvee Please write one and raise a PR. You don't need to an assignee to write one as mentioned in the description of issue.

**Comment by SamikLalwani** [comment]
Can I work on this blog too, could you please assign me too?

**Comment by SamikLalwani** [comment]
Where can we write the blog, i also want to contribute?

**Comment by gabrielrab** [comment]
Hello Maintainers,
I wrote a blog post, and I would like you to please add this issue for participation in Hacktoberfest. Thank you!

[My PR](https://github.com/LoginRadius/engineering-portal/pull/355)

**Comment by SamikLalwani** [comment]
Blog done #360

**Comment by hyperyuri** [comment]
Hello There!
I wrote a blog post <a href="https://github.com/LoginRadius/engineering-portal/pull/361">This is my PR </a>
Can you please add this issue for Hacktoberfest participation? Thank you all!

**Comment by aryanrawlani28** [comment]
Hello! Wrote a blogpost, would appreciate your thoughts. https://github.com/LoginRadius/engineering-portal/pull/363

Cheers!

**Comment by shreyaa-sharmaa** [comment]
Hello! Wrote a blog on end-to-end testing with jest-puppeteer #364 
Thanks!

**Comment by baspalinckx** [comment]
Hi! Made a PR for my blog about EternalBlue. Hope it's up to spec https://github.com/LoginRadius/engineering-portal/pull/366
Thanks!

**Comment by sudiptog81** [comment]
Added a blog in #359. Thanks.

**Comment by krabhisharma** [comment]
hey I want to write a blog  can I contribute to it?

**Comment by puneetsingh24** [comment]
Hello, @krabhisharma Thanks for your interest in writing the blog. Please feel free to write one and let us know here once you raise a PR.

Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well. Happy Writing :)

**Comment by arshita129** [comment]
Hey!  Please see my PR #352 

Thank you

**Comment by krabhisharma** [comment]
@puneetsingh24   You can review my PR #376

**Comment by Ninjavin** [comment]
@puneetsingh24 I have opened a Pull Request #338 with reference to this issue.

**Comment by AshishMhrzn10** [comment]
@puneetsingh24  I have opened a PR #381 contributing to this issue. Please review it.

**Comment by ng29** [comment]
hey I want to write a blog can I contribute to it?

**Comment by amoghatsunil** [comment]
@pareek-narendra I would like to write a blog on ROS

**Comment by puneetsingh24** [comment]
Hello, @ng29 @amoghatsunil  Thanks for your interest in writing the blog. Please feel free to write one and let us know here once you raise a PR.

Also please go through https://www.loginradius.com/engineering/page/hacktoberfest2020 to get free swags from LoginRadius as well. 
Happy Writing :)

**Comment by prithvirajbytes** [comment]
Added a blog in #391. Please review.

**Comment by prithvirajbytes** [comment]
Added a blog in #392 . Please review and help me contribute. :)

**Comment by Devanshh** [comment]
Hi, Please have a look at #393 
Happy to Help and Contribute towards the Community!

**Comment by Malvika18** [comment]
Hi ,please check my PR #395

**Comment by ng29** [comment]
hi @puneetsingh24 / @pareek-narendra 

Please find my pr https://github.com/LoginRadius/engineering-portal/pull/396

Cheers,

**Comment by krabhisharma** [comment]
please check PR #399

**Comment by malathit** [comment]
@puneetsingh24 @pareek-narendra @vyasriday Wrote a post on using Jekyll to setup a blog in PR #401 . Please review and let me know your thoughts

**Comment by X3NOSIZ** [comment]
@pareek-narendra @vyasriday assign me please!

**Comment by prithvirajbytes** [comment]
@pareek-narendra @puneetsingh24 @vyasriday  Please review #392 and let me contribute

**Comment by Devanshh** [comment]
@pareek-narendra @vyasriday @puneetsingh24 Can you please check my blog post. The PR is #410

**Comment by sharur7** [comment]
@pareek-narendra @vyasriday @puneetsingh24 Can you please review my PR #420

**Comment by Hackerbone** [comment]
@pareek-narendra @vyasriday @puneetsingh24  Submitted PR #424 . Please review! Thanks

**Comment by bharrod321** [comment]
Submitted PR #430  for review.  Thank you.

**Comment by Rishav139** [comment]
Submitted my blog on Blockchain and how it works. PR #433 Please review it @pareek-narendra @vyasriday @puneetsingh24 
Thanks

**Comment by Madmaxcoder2612** [comment]
Submitted my Blog on Arduino based Bluetooth Car with code. PR #414 , Please review it @vyasriday  @pareek-narendra @puneetsingh24  Thank you

**Comment by prabhatkgupta** [comment]
I have submitted a blog on Basics of Kubernetes. PR #435 , Please review it and provide any feedback for improvement or changes@vyasriday @pareek-narendra @puneetsingh24

**Comment by devkapilbansal** [comment]
Hi @pareek-narendra please assign this to me

**Comment by devkapilbansal** [comment]
I have submitted a PR for GitHub APIs. Please review #472 and provide your valuable feedback. @pareek-narendra @puneetsingh24

**Comment by AnshMishra2001** [comment]
@pareek-narendra Can I work on this issue ?

**Comment by AnshMishra2001** [comment]
Created PR #480

**Comment by saranicoly** [comment]
Submitted PR #484  for review. Thank you.

**Comment by 21Rutam** [comment]
Hey, submitted PR #485 to dev for merging. Thank you and awaiting the swags 🤩

**Comment by AnshMishra2001** [comment]
Created PR #483

**Comment by Rishav139** [comment]
Will PRs with 'hactoberfest accepted' label be merged?
@pareek-narendra @puneetsingh24
