### ISSUE TITLE
Put detail about argon2 hashing in the blog post about encryption and hashing

### ISSUE THREAD

**Issue by puneetsingh24** [LoginRadius/engineering-portal#234]
https://www.loginradius.com/engineering/blog/encryption-and-hashing/

The above blog contains introductory detail about many hashing and encryption algorithms, Need to add the details about argon2 hashing also

**Comment by JanetLaysEggs** [comment]
@puneetsingh24 could you please issue this task to me please?

**Comment by kichloo** [comment]
@puneetsingh24 I would like to work on this one!

**Comment by JanetLaysEggs** [comment]
@puneetsingh24 or anyone,  could you please checkout that commit above and see if the paragraphs about Argon2 are up to standard?
