### ISSUE TITLE
Need to update the dimension of the blog post cover image

### ISSUE THREAD

**Issue by puneetsingh24** [LoginRadius/engineering-portal#237]
https://www.loginradius.com/engineering/blog/index-in-mongodb/

The cover image for the above blog is of not recommended size, You can upload a new image or update the cover image of the above mention blog to 3:2 ratio and minimum size to 1200px:800px

**Comment by hastagAB** [comment]
Hi @puneetsingh24 ,
I would like to fix this issue. Should I replace the Cover image with MongoDB logo image of required size?

**Comment by puneetsingh24** [comment]
Assigned you @hastagAB . MongoDB logo with a nice background will work.

And LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020

**Comment by Harshsngh07** [comment]
Hi @puneetsingh24  is this issue still on? Would like to work on it.

**Comment by Garvit-32** [comment]
Hi @puneetsingh24, I would like to work on this issue

**Comment by priyanka1111** [comment]
Hi @puneetsingh24, this issue is open? Would like to work.

**Comment by puneetsingh24** [comment]
Issue has been done
