### ISSUE TITLE
Padding issue in the card

### ISSUE THREAD

**Issue by rishipurwar1** [LoginRadius/engineering-portal#249]
On the homepage, the padding on the card is too much.
We need to decrease it.

Screenshot
![Shot 0009](https://user-images.githubusercontent.com/57035408/94528626-4a2f7800-0256-11eb-8ecd-1c33881cf182.png)

**Comment by rishipurwar1** [comment]
I would like to work on this issue

**Comment by vyasriday** [comment]
Hey, @rishipurwar1 Please add details of the device and browser you are using.  Are you using a mobile browser?

**Comment by rishipurwar1** [comment]
Hello @vyasriday I am using windows 10 and google chrome

**Comment by vyasriday** [comment]
From your screenshot, it looks like you are viewing it on a mobile browser or at least in the mobile view.

**Comment by rishipurwar1** [comment]
No, I cropped the screenshot...

**Comment by vyasriday** [comment]
@rishipurwar1 I discussed the issue with our design team and looks like they don't think the current design has any issues regarding padding. I am sorry, but I don't think this is a valid issue. I will be closing this. :)
