### ISSUE TITLE
Need to add Deploy status badge in README.md

### ISSUE THREAD

**Issue by akshay-js** [LoginRadius/engineering-portal#311]
Please add the Deploy status badge in README.md 

Status badges are visual representations of your site's status, served as image files you can add to repository READMEs, documentation, or any other web page. Please follow this [URL](https://docs.netlify.com/monitor-sites/status-badges/#add-status-badges)

**Comment by malakar-soham** [comment]
I can take up this issue

**Comment by just-tech20** [comment]
@akshay-s-770  want to work on this issue.
We can use shields.io to add badge in Readme.md

**Comment by DevLokCodes** [comment]
i would love to work on this could you assign this issue to me

**Comment by gagandeepp** [comment]
@akshay-js  Please assign this to me
