### ISSUE TITLE
Create a contributing guidelines

### ISSUE THREAD

**Issue by shraddhavp** [LoginRadius/engineering-portal#314]
@puneetsingh24  would like to create a contributing.md file 
similar to https://github.com/smaranjitghose/awesome-portfolio-websites/blob/master/CONTRIBUTING.md  which I have only created if you are ok with the design I woud like to design contributing.md file for this project too please assign the issue to me

**Comment by puneetsingh24** [comment]
Hello @shraddhavp We already have contributing guidelines, however, if you can make it much better you are welcome to work on it. Just remember that we are not accepting typos/grammatical fixes. And there should not be any loss of information.

Happy Coding!

**Comment by OmkarPh** [comment]
Hello 
Is @shraddhavp working on this?
If not, I might want to give it a try.

**Comment by shraddhavp** [comment]
> Hello
> Is @shraddhavp working on this?
> If not, I might want to give it a try.

@OmkarPh  I am working on it sorry!

**Comment by OmkarPh** [comment]
Fine, I saw you didn't comment anything since 8 days, so thought of trying 😅✌️
