### ISSUE TITLE
Adding ESLint and Prettier GitHub Actions

### ISSUE THREAD

**Issue by iamrajiv** [LoginRadius/engineering-portal#348]

**Comment by iamrajiv** [comment]
@puneetsingh24 I want to work on this issue.

**Comment by vyasriday** [comment]
@iamrajiv Could you please add more description to it. How it will add value to this Repository?

**Comment by iamrajiv** [comment]
@vyasriday I have updated the description please take a look.

**Comment by M4yankChoudhary** [comment]
Can i take this ?
