### ISSUE TITLE
Write a tech blog post. Get published on Async Blog. And win branded swag.

### ISSUE THREAD

**Issue by raghunath-r-a** [LoginRadius/engineering-portal#750]
Hello Everyone 👋

We're accepting long-form (min. 1000 words) blog posts on the following topics. Each contributor will get editorial support and guidance throughout the process 🙂

If you want to work on any topic not listed here, please do let us know by mentioning @raghunath-r-a. We'll discuss and see how we could proceed.

#### Topics

- https://github.com/LoginRadius/engineering-portal/issues/751
- https://github.com/LoginRadius/engineering-portal/issues/752
- https://github.com/LoginRadius/engineering-portal/issues/753
- https://github.com/LoginRadius/engineering-portal/issues/754
- https://github.com/LoginRadius/engineering-portal/issues/755
- https://github.com/LoginRadius/engineering-portal/issues/756
- https://github.com/LoginRadius/engineering-portal/issues/757
- https://github.com/LoginRadius/engineering-portal/issues/758
- https://github.com/LoginRadius/engineering-portal/issues/759
- https://github.com/LoginRadius/engineering-portal/issues/760
- https://github.com/LoginRadius/engineering-portal/issues/761
- https://github.com/LoginRadius/engineering-portal/issues/762
- https://github.com/LoginRadius/engineering-portal/issues/763
- https://github.com/LoginRadius/engineering-portal/issues/764
- https://github.com/LoginRadius/engineering-portal/issues/765
- https://github.com/LoginRadius/engineering-portal/issues/782
- https://github.com/LoginRadius/engineering-portal/issues/783
- https://github.com/LoginRadius/engineering-portal/issues/784

**Please comment on the specific issue if you want to work on a particular title. We'll then assign it to you.**

For writing the blog post, please follow the [blog writing guidelines.](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md)

Once you have drafted the blog post, please raise a pull request using [the guidelines here](https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md).

After you raise the pull request, we'll review it in terms of technical accuracy and content quality. And we'll request any changes necessary from you. Once finalized, we'll publish the blog under your name.

_[Async Blog](https://www.loginradius.com/blog/async/) is for developers by developers -- it's a place for developers to share their expertise and find solutions for the problems they're facing._

Feel free to ask any questions 🤞

**Comment by ogolajecinta** [comment]
Hi, I would like to work on this topic: How to Improve User Experience with Passwordless Authentication

**Comment by McTechie** [comment]
Hey @raghunath-r-a, I'd like to work on the title: `What Are Refresh Tokens? When & How to Use Them`

**Comment by raghunath-r-a** [comment]
> Hey @raghunath-r-a, I'd like to work on the title: `What Are Refresh Tokens? When & How to Use Them`

Please [comment here](https://github.com/LoginRadius/engineering-portal/issues/753), so I can assign it to you

**Comment by raghunath-r-a** [comment]
> Hi, I would like to work on this topic: How to Improve User Experience with Passwordless Authentication

Please [comment here](https://github.com/LoginRadius/engineering-portal/issues/754), so I can assign it to you

**Comment by saisumanthkumar** [comment]
Hi,@raghunath-r-a
I would like to work on this topic : Bootstrap 4 vs. Bootstrap 5: What is the Difference?

**Comment by vibhuvj27** [comment]
Hey @raghunath-r-a, Can I write on this topic: OpenCV Python Basics?

**Comment by AmreshSinha** [comment]
@vibhuvj27 I thnink "Integrating OpenCV with WebApps" would be a better option!

**Comment by vibhuvj27** [comment]
> @vibhuvj27 I thnink "Integrating OpenCV with WebApps" would be a better option 👍

Oh yea that's better!!
Thanks

**Comment by mohitsaxenaknoldus** [comment]
Hello, can I write a complete blog on JWT? I'll give complete information, its format, and examples.

**Comment by ps-19** [comment]
Assign me issue#760 please.

**Comment by raghunath-r-a** [comment]
@vibhuvj27 This title sounds good: How to Integrate OpenCV with Web Apps

I have created an issue for the same: https://github.com/LoginRadius/engineering-portal/issues/797

Please comment on the issue, so I can assign it to you.

**Comment by raghunath-r-a** [comment]
> Hello, can I write a complete blog on JWT? I'll give complete information, its format, and examples.

@mohitsaxenaknoldus We have already covered well about JWT here: https://www.loginradius.com/blog/async/tags/jwt/

Please do let us know if you want to cover anything that isn't available on our blog yet. Thanks!

**Comment by mohitsaxenaknoldus** [comment]
> > Hello, can I write a complete blog on JWT? I'll give complete information, its format, and examples.
> 
> @mohitsaxenaknoldus We have already covered well about JWT here: https://www.loginradius.com/blog/async/tags/jwt/
> 
> Please do let us know if you want to cover anything that isn't available on our blog yet. Thanks!

What about email using Lambda and Amazon SES?

Ok so what about `sending email using Lambda and Amazon SES`? This will also involve the use of IAM.

**Comment by tushartiwari7** [comment]
Hey @raghunath-r-a, I was planning to write an article on `JavaScript for Competitive Programming`. Let's see if we can make it together.

**Comment by raghunath-r-a** [comment]
Hey @tushartiwari7 It is a good topic. However, our blog mainly focuses on web development and user authentication (though we also welcome other topics at times). 

Although I myself am not an avid programmer, I don't think JavaScript is the go-to option for programming competitions (Please correct me If I'm wrong).

I see that you've worked on a project related to cryptography. Would you be interested in something related to authentication security, or what kind of signing algorithms are better for implementing user authentication, etc.? Something on those lines would be better, I think. 

Would you please let me know your thoughts on this?

**Comment by raghunath-r-a** [comment]
> 
> 
> > > Hello, can I write a complete blog on JWT? I'll give complete information, its format, and examples.
> > 
> > 
> > @mohitsaxenaknoldus We have already covered well about JWT here: https://www.loginradius.com/blog/async/tags/jwt/
> > Please do let us know if you want to cover anything that isn't available on our blog yet. Thanks!
> 
> Ok so what about `sending email using Lambda and Amazon SES`? This will also involve the use of IAM.

@mohitsaxenaknoldus You mean, `how to send transactional emails using Lambda and Amazon SES`?

If yes, please do create an issue with this title, so I can assign it to you.

**Comment by tushartiwari7** [comment]
> Hey @tushartiwari7 It is a good topic. However, our blog mainly focuses on web development and user authentication (though we also welcome other topics at times).
> 
> Although I myself am not an avid programmer, I don't think JavaScript is the go-to option for programming competitions (Please correct me If I'm wrong).
> 
> I see that you've worked on a project related to cryptography. Would you be interested in something related to authentication security, or what kind of signing algorithms are better for implementing user authentication, etc.? Something on those lines would be better, I think.
> 
> Would you please let me know your thoughts on this?

Thanks alot @raghunath-r-a for your words on this. 
It's true that javascript is not the go-to language for programming challanges due to language constraints as it's a Scripting language. I wanted to cover it in detail that's why planning to write on it.

And yes, I have did a project on cryptography too but for the time being I want to do development in MERN. 

Will get in touch with you if planned to do some Auth stuff, Thanks again ✌

**Comment by raghunath-r-a** [comment]
This issue is being closed as Hacktoberfest has ended.
