### ISSUE TITLE
What Are Refresh Tokens? When & How to Use Them

### ISSUE THREAD

**Issue by raghunath-r-a** [LoginRadius/engineering-portal#753]

**Comment by McTechie** [comment]
Heyy @raghunath-r-a ,  I'd like to take up this blog post!

**Comment by raghunath-r-a** [comment]
Hey @McTechie This is now assigned to you. Please proceed with an outline and then drafting the blog post. 

If you're stuck anywhere or having doubts, please do let us know.

**Comment by McTechie** [comment]
Fixed in #778

**Comment by raghunath-r-a** [comment]
Hi @McTechie We published your blog some time ago: https://www.loginradius.com/blog/async/guest-post/what-are-refresh-tokens-and-when-to-use-them/

I just thought to let you know in case you missed it. 

Please do share it with your network and on social media!

**Comment by McTechie** [comment]
Yess @raghunath-r-a, I did see the published blog and was super proud of myself for having written it! xD

P.s. Super glad to have contributed to this fabulous repository as well! Looking forward to further contributions to LoginRadius 🙌🏼
