### ISSUE TITLE
What are JWT, JWS, JWE, JWK, and JWA?

### ISSUE THREAD

**Issue by raghunath-r-a** [LoginRadius/engineering-portal#758]

**Comment by JubayerJoy** [comment]
Hi @raghunath-r-a, I'm interested in working on this.
Cheers 🎈

**Comment by raghunath-r-a** [comment]
Hi @JubayerJoy 

This is now assigned to you. Please proceed with an outline and then drafting the blog post.

If you're stuck anywhere or having doubts, please do let us know.

**Comment by JubayerJoy** [comment]
@raghunath-r-a, thank you for assigning.

I will follow [this](https://datatracker.ietf.org/doc/html/rfc7515) documentation, your [guidelins](https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md), and [this LoginRadius blog](https://www.loginradius.com/blog/async/guest-post/jwt-vs-sessions/) for standards for the blog.

Do you prefer any other material for this?
Cheers.

**Comment by raghunath-r-a** [comment]
That's all sounds good, @JubayerJoy 

Just try making it as developer-friendly as possible and very explanatory. It will provide deep value for the developer community as a whole.

**Comment by raghunath-r-a** [comment]
Hi @anushkajain6459 It is currently assigned to @JubayerJoy 

You can propose some other topics you'd like to write about that are related to web development.

**Comment by Yashesvinee** [comment]
Hi I have added the blog 
Please let me know if it requires any changes

**Comment by raghunath-r-a** [comment]
Hi @Yashesvinee Congrats! Your blog has been published: https://www.loginradius.com/blog/async/guest-post/what-are-jwt-jws-jwe-jwk-jwa/

Please do share it with your network and on social media

**Comment by Yashesvinee** [comment]
Thank you Sir
