### ISSUE TITLE
Add Github Issue Form

### ISSUE THREAD

**Issue by Hard-Coder05** [LoginRadius/engineering-portal#795]
__Is your feature request related to a problem? Please describe.__

GitHub has recently rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature. This would allow you to create interactive issue templates and validate them 🤯.

__Describe the solution you'd like__

This repository currently uses no issue template. Your task is to create GitHub issue forms for this repository. We can use standard issue templates as a reference for this PR.

**Comment by Hard-Coder05** [comment]
@raghunath-r-a I would like to work on this issue!

**Comment by raghunath-r-a** [comment]
Hi @Hard-Coder05 Thanks so much for raising this issue! This is now assigned to you. You may please proceed to work on this.

**Comment by Hard-Coder05** [comment]
@raghunath-r-a I have made the PR for this! Do let me know if any change is required!
