### ISSUE TITLE
How to Integrate OpenCV with Web Apps

### ISSUE THREAD

**Issue by raghunath-r-a** [LoginRadius/engineering-portal#797]

**Comment by vibhuvj27** [comment]
Can you please assign this to me @raghunath-r-a

**Comment by raghunath-r-a** [comment]
@vibhuvj27 This is now assigned to you. Please proceed with an outline and then drafting the blog post.

If you're stuck anywhere or having doubts, please do let us know.

**Comment by rohiraanjali** [comment]
Can you please assign this to me @raghunath-r-a

**Comment by raghunath-r-a** [comment]
Hi @dingusagar 

This is already assigned to @vibhuvj27 for now.

**Comment by dingusagar** [comment]
Oh okay. I thought the previous assignment was removed. No problem.

**Comment by Aryannath** [comment]
Hey @raghunath-r-a  is this still up ?

**Comment by raghunath-r-a** [comment]
> 
> 
> Oh okay. I thought the previous assignment was removed. No problem.

Oh, I'm sorry. I didn't see the update that @vibhuvj27 had self-unassigned. As this is the case, I'm assigning this to you.

**Comment by raghunath-r-a** [comment]
> 
> 
> Hey @raghunath-r-a is this still up ?

Hey @Aryannath This is assigned to @dingusagar for now. Please let us know if you'd like to write on some other topic.

**Comment by dingusagar** [comment]
hi @raghunath-r-a . Is there any example blogs that i can refer to for a template ? Also where should i be doing the draft work?

**Comment by raghunath-r-a** [comment]
Hi @dingusagar Congrats! You blog has been published: https://www.loginradius.com/blog/async/guest-post/opencv-web-app-with-streamlit/

**Comment by dingusagar** [comment]
@raghunath-r-a ,
Thanks a lot for the support. This was my first blog. Now I am motivated to write more. 😊

**Comment by raghunath-r-a** [comment]
Hey @dingusagar That's good to know. You wrote it well. To me, it didn't feel like it's your first blog! 

What are you interested in writing about?

Keep contributing!
@raghunath-r-a

**Comment by dingusagar** [comment]
Sure, will checkout other topics and contribute if it interests me. My interests vary from nlp, computer vision, python automations etc.

**Comment by raghunath-r-a** [comment]
Sure. If we didn't list any topic you wanna write about, please do let us know.
