### ISSUE TITLE
Blog: How to send transactional emails using Lambda and Amazon SES

### ISSUE THREAD

**Issue by mohitsaxenaknoldus** [LoginRadius/engineering-portal#804]
Please assign it to me @raghunath-r-a 

One question: Which format do I've to provide the blog in? google doc? or I just have to put here?

**Comment by raghunath-r-a** [comment]
@mohitsaxenaknoldus This is now assigned to you. Please proceed with an outline and then drafting the blog post.

If you're stuck anywhere or having doubts, please do let us know.

The blog shall be in markdown format. Please find more details here: 

- https://github.com/LoginRadius/engineering-portal/blob/master/CONTRIBUTING.md
- https://github.com/LoginRadius/engineering-portal/blob/master/GUIDELINES.md

**Comment by mohitsaxenaknoldus** [comment]
PR raised: https://github.com/LoginRadius/engineering-portal/pull/813
@raghunath-r-a

**Comment by mohitsaxenaknoldus** [comment]
Ooops...missed those! Added now! @raghunath-r-a
